---
title: "Target trial framework"
sidebar: false
---

# Goals

- Communicate benefits of using the target trial framework to design the analysis of an observational study
- Practice the process of reading an academic journal article


<br><br><br><br>


# Discussion

The following prompts are adapted from the following guides for reading scholarly articles:

- Brown University's guide [How to Read a Scholarly Article](https://libguides.brown.edu/evaluate/Read)
- [How to Read the Statistical Methods Literature: A Guide for Students](https://faculty.washington.edu/heagerty/Courses/b572/public/Murphy2007.pdf)


Read through the following prompts, and then open [this Google Doc](https://docs.google.com/document/d/1AV9NZPJXEt6uw16uvWbDdfZWquOBwrE2H11QPLd4zBA/edit?usp=sharing) to record notes as you re-engage with today's article: [Specifying a target trial prevents immortal time bias and other self-inflicted injuries in observational analyses](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5124536/pdf/nihms-790601.pdf).

1. Reread the title, abstract, keywords, and introduction
    - Based on this information, write a 2 sentence description of the problem the article is trying to address.

2. Make note of the authors
    - You might see the same authors repeatedly when exploring other articles referenced in the article. This helps you understand the breadth of topics that certain authors write about.

3. Find a problem or context that you are familiar with and relate the article's arguments to this context.
    - For example, it could help to start with the context of a randomized experiment. As you read, ask yourself "What is different about the target trial approach?"

4. As you skim the article again:
    - Write down unfamiliar jargon to look up later. If a sentence makes a claim that is hard to understand, try to find another concept or term in that sentence or in a nearby sentence that you do understand.
    - If an unfamiliar concept is linked to a citation, write down that citation and categorize that citation as essential (top priority for what to read next) or secondary.

5. As you reread the article:
    - What arguments were hard to follow?
    - What could the authors have done to make it easier for you to understand the article? Any such instances are good candidates for inclusion in your own communications about related ideas.
