project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!templates/"
  resources:
    - "data/*.csv"

website:
  title: "STAT 451"
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - file: schedule.qmd
        text: "Schedule"
      - file: syllabus.qmd
        text: "Syllabus"
      - sidebar:activities
      - file: assignments.qmd
        text: "Assignments"
      - file: project.qmd
        text: "Project"

  sidebar:
    - id: activities
      title: "Activities"
      contents:
        - 01-introductions.qmd
        - 02-identification.qmd
        - 03-causal-graphs-intro.qmd
        - 04-causal-graphs-simulation.qmd
        - 05-causal-graphs-identification.qmd
        - 06-causal-graphs-testing.qmd
        - 07-rct.qmd
        - 08-target-trial.qmd
        - 09-matching-part1.qmd
        - 09-matching-part2.qmd
        - 10-weighting.qmd
        - 11-rdd.qmd
        - 12-es-its-synth.qmd
        - 13-fe.qmd
        - 14-did.qmd
        - 15-sensitivity-analyses.qmd
  
  page-footer:
    left: |
      &copy; Leslie Myint, 2024<br>
      All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    code-overflow: wrap

editor: source
