---
title: "Assignments"
sidebar: false
---

These assignments will build up your Portfolio. Recall from the [syllabus](syllabus.qmd#portfolio) that the goal of the Portfolio is create a reference that is tailored to the way that you think about and understand ideas.

I hope that you feel proud of your Portfolio by the end of the semester. If you want to publish it, the Quarto files (`.qmd`) that you submit for your assignments can become the basis for a website that looks a lot like this course website or websites in the [Quarto gallery](https://quarto.org/docs/gallery/#websites). I'm happy to help you get this set up if you're interested.



<br><br>



# Assignment 1

**Due Wednesday, 9/11 at 5pm on [Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=129327)**

This first assignment is a short writing piece for me to get to know you. There are no length requirements---just use as many words as needed to convey what you want, and feel free to respond to my questions in any order.

**Format:** Please submit a link to a Google Doc (preferred) or a Word document. (No PDFs because comments end up being too scrunched in PDFs.) If submitting a Google Doc, make sure that I am added with either Editing or Commenting privileges. 

**Prompt:**

I recently read a moving essay called [An Education of His Own](https://lathamt.substack.com/p/an-education-of-his-own) by writer Latham Turner. I invite you to read this essay as you think about what you might want from this course experience. If you feel so moved, I'd love to hear what parts of the essay resonated with you.

What would make this course of a success for you? What are you hoping to learn and accomplish? I know that there are a variety of reasons for taking the course, and I want to better understand how those reasons inform what you are hoping for.

Reflect on other courses you've taken and other learning environments in which you've participated. What grading/motivation/incentive structures, classroom dynamics, and personal habits/practices were helpful for your learning? What hindered your learning?

For the next questions, I want to be honest with you about where I am coming from. I mentioned in the [syllabus](syllabus.qmd#my-philosophy) that if I didn't have to give grades, I wouldn't. The act of grading (putting points and A/B/C-like marks on work) is quite draining for me because I feel immense pressure to be fair, be "accurate" (even though there is no way that something like a grade could accurately measure something as complex as learning), and keep your motivation levels high. I also feel that grading creates a charged power dynamic between the instructor and the student that I don't like. I became a teacher because I love being a guide and a coach for students in ideas I find fascinating---not because I wanted to bestow judgment.

If my aversion to grades seems like an aversion to high expectations for your learning, it's not. It's an aversion to what I see as a very problematic system when something more simple and more meaningful encourages learning so well: qualitative feedback. Note that grading is very different from qualitative feedback, which, simply put, is a collection of thoughtful comments on your work. I truly enjoy giving feedback when it is not tied to a grade. There's so much rich information in qualitative feedback that grades, by virtue of being a single letter or number, can't capture.

With that background from me, I have a few questions for you: How would you feel about a system in which everyone gets an A so that we can ignore grades completely and focus on qualitative feedback? How would you feel about a system in which everyone was graded differently? How do you think we should approach the process of deciding to how to handle grades in this course?

I know that the background I gave suggests what I would prefer for what we do with grades. I know that this may affect your comfort in being honest, but I truly do want to know your honest thoughts.

Thanks for taking the time to reflect and share with me. I'm looking forward to reading what you write.



<br><br>



# Assignment 2

**Due Friday, 9/27 at 5pm on [Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=129329)**

Imagine that you are preparing your capstone talk on your project from this course. The start of that presentation should probably include a section that introduces orients them to what the course is even about: What *is* causal inference? What are causal graphs, and what role do they play in causal inference?

**Task:** Create slides for this presentation section. Add presenter notes beneath each slide to indicate what you would say. If you wish, you can record a video of you giving this presentation segment.

**Audience:** Aim for this presentation segment to be accessible to students who have taken STAT 155 but no upper-level courses.

**Format:**

- For submitting slides, Google Slides is preferred---make sure that I am added with either Editing or Commenting privileges. If using another program for slides, submit both the slides and presenter notes beneath in PDF format.
- If submitting a video, upload the video or share a link where I can access it.

## Addressing feedback

**Due Wednesday, October 9 on [Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=139487)**

Address feedback on your slides by doing the following:

1. Write a paragraph summarizing the changes that you made and/or intend to make and why
2. Implement changes to your slides and/or presenter notes in light of feedback.
    - You don't need to agree with everything I recommend!
    - And you may not have time to implement everything that I recommend even if you agree.
    - Make the changes that you are able to, being mindful of your time and other commitments.
    - Whatever you want to address but cannot finish by the due date, tell me about in your paragraph.



<br><br>


# Assignment 3

**Due Wednesday, October 9 on [Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=139488)**

Download [this template](templates/assignment3.qmd). All instructions and exercises are contained in that file.



<br><br>



# Assignment 4

**Due Wednesday, October 30 on [Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=142395) as a Word document (or a Google Doc).** (Not a PDF because it's harder to write longer comments on a PDF.)

Identify a causal research question that you would be interested in pursuing if you chose the data analysis option for the final project.

Consider the following study designs/methods that we have examined so far:

- Randomized experiment/target trial: For this one, when addressing the questions below, talk about the randomized experiment that you would ideally run to estimate the causal effect and why it likely isn't feasible. When talking about the target trial emulation framework, talk about whether a relevant outcome for your research question is a *time-to-event* outcome (the time until some event occurs) and thus whether it would be useful to go through a target trial emulation process.
- Matching
- Weighting
- Regression discontinuity
- Interrupted time series
- Synthetic control

For each of the above study designs/methods, answer the following questions:

- In big picture terms, how does this study design/method work? What's the main idea behind its strategy for identifying the causal effect?
- What are advantageous features of this design/method? What are limitations/drawbacks?
- How could you use this design/method for your research question? What data would you need to have access to? Do you think it would be feasible to use this design/method?




<br><br>





<!-- # Assignment 4 -->

<!--
General questions applicable to all study designs/methods
- What is this study design/method? What's the main idea behind it?
- When would we use this design/method? What are its advantageous features?
- How do we analyze data from this design/method?
- What are some limitations/drawbacks of this design?
-->
